name: Auto PR Merge for Personal Pages

on:
  pull_request_target:
    types:
      - labeled

jobs:
  auto-pr-merge:
    name: "Auto PR merge (v1.4)"
    if: contains(github.event.pull_request.labels.*.name, 'request-merge')
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Check PR permission
        run: gh pr view ${{github.event.pull_request.number}} --json author,files | python .github/scripts/check_permission.py

      - name: Approve PR
        run: gh pr review ${{github.event.pull_request.number}} --approve 

      - name: Merge PR
        if: ${{! github.event.pull_request.draft}}
        run: gh pr merge ${{github.event.pull_request.number}} -m
