name: Auto PR Merge for Personal Pages

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  auto-pr-merge:
    name: "Auto PR merge (v1.0)"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.OKADALAB_GITHUB_ACTIONS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Check PR permission
        run: gh pr view ${{github.event.pull_request.number}} --json author,files | python .github/scripts/check_permission.py

      - name: Merge PR
        if: ${{! github.event.pull_request.draft}}
        run: gh pr merge ${{github.event.pull_request.number}} -m
